const GET_DATA_DASHBOARD = 'GET_DATA_DASHBOARD';
const GET_DATA_SERVICE = 'GET_DATA_SERVICE';
const LOAD_DATA_DASHBOARD = 'LOAD_DATA_DASHBOARD';
const ERROR_DASHBOARD = 'ERROR_DASHBOARD';
const LOAD_PATIENT = 'LOAD_PATIENT';
const SHOW_PATIENT = 'SHOW_PATIENT';


export {GET_DATA_DASHBOARD,GET_DATA_SERVICE,LOAD_DATA_DASHBOARD,ERROR_DASHBOARD,LOAD_PATIENT,SHOW_PATIENT}