const GET_DATA_DASHBOARD = 'GET_DATA_DASHBOARD';
const ADD_DASHBOARD = 'ADD_DASHBOARD';
const GET_DATA_SERVICE = 'GET_DATA_SERVICE';
const LOAD_DATA_DASHBOARD = 'LOAD_DATA_DASHBOARD';
const ERROR_DASHBOARD = 'ERROR_DASHBOARD';
const LOAD_PATIENT = 'LOAD_PATIENT';
const SHOW_PATIENT = 'SHOW_PATIENT';
const SHOW_ORG = 'SHOW_ORG';
const ERROR_ORG = 'ERROR_ORG';
const ERROR_DEPARTMENT = 'ERROR_DEPARTMENT';
const LOAD_DEPARTMENT = 'LOAD_DEPARTMENT';
const SHOW_DEPARTMENT = 'SHOW_DEPARTMENT';
const DELETE_CONTRACT = 'DELETE_CONTRACT';
const ADD_SERVICE = 'ADD_SERVICE';
const ERROR_SERVICE = 'ERROR_ADD_SERVICE';
const SHOW_SERVICE = 'SHOW_SERVICE';
const DELETE_SERVICE = 'DELETE_SERVICE';
const EDIT_SERVICE = 'EDIT_SERVICE';
const ADD_PATIENT = 'ADD_PATIENT';
const ERROR_PATIENT = 'ERROR_PATIENT';
const LOGIN_USER = 'LOGIN_USER';
const REGISTER_USER = 'REGISTER_USER';
const ERROR_AUTH = 'ERROR_AUTH';
const LOAD_AUTH = 'LOAD_AUTH';
const LOGOUT_USER = 'LOGOUT_USER';
const RESET_PASSWORD = 'RESET_PASSWORD';
const GET_EDIT_CONTRACT = 'EDIT_CONTRACT';
const UPLOAD_CONTRACT = 'UPLOAD_CONTRACT';
const EDIT_CONTRACT = 'EDIT_CONTRACT';
const GET_TYPE = 'GET_TYPE';
const LOAD_TYPE = 'LOAD_TYPE';


export {GET_DATA_DASHBOARD,
    GET_DATA_SERVICE,
    LOAD_DATA_DASHBOARD,
    ERROR_DASHBOARD,
    LOAD_PATIENT,
    SHOW_PATIENT,
    SHOW_ORG,
    ERROR_ORG,
    LOAD_DEPARTMENT,
    SHOW_DEPARTMENT,
    ERROR_DEPARTMENT,
    ADD_DASHBOARD,
    DELETE_CONTRACT,
    ADD_SERVICE,
    ERROR_SERVICE,
    SHOW_SERVICE,
    DELETE_SERVICE,
    EDIT_SERVICE,
    ADD_PATIENT,
    ERROR_PATIENT,
    LOGIN_USER,
    REGISTER_USER,
    ERROR_AUTH,
    LOAD_AUTH,
    LOGOUT_USER,
    RESET_PASSWORD,
    EDIT_CONTRACT,
    UPLOAD_CONTRACT,
    GET_EDIT_CONTRACT,
    GET_TYPE,
    LOAD_TYPE
}